### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by rphelan** [hammerjs/jquery.hammer.js#1]
Need to tag v1.0.0 so bower can find it.  Here's the output from Bower currently:

bower jquery-hammerjs#~1.0.0     ENORESTARGET No tag found that was able to satisfy ~1.0.0

**Comment by p16i** [comment]
bump++

**Comment by boulox** [comment]
+1  please create tag to enable install with bower

**Comment by jtangelder** [comment]
fixed
