### ISSUE TITLE
Uncaught TypeError: Cannot read property 'timeStamp' of undefined 

### ISSUE THREAD

**Issue by urbany** [hammerjs/jquery.hammer.js#10]
Sometimes I get the error:
Uncaught TypeError: Cannot read property 'timeStamp' of undefined 

In this line: https://github.com/EightMedia/jquery.hammer.js/blob/4ccab20ce569e1fe257d48860858d8bf4421a19c/jquery.hammer-full.js#L1310

It happens when I finish dragging a sidebar (holding a button that has a tap event) and quickly click another button that has a tap event.

Replacing:

``` javascript
since_prev = prev && ev.timeStamp - prev.lastEvent.timeStamp;
```

with

``` javascript
since_prev = prev && prev.lastEvent && ev.timeStamp - prev.lastEvent.timeStamp;
```

solves the issue.

**Comment by jtangelder** [comment]
fixed in the hammer.js source, when released it is also fixed in the jquery version.

**Comment by urbany** [comment]
Thanks mate, will post in the primary project next time. Cheers.

**Comment by jtangelder** [comment]
no problem! the fix is released, in case you didnt noticed.

**Comment by jjcordova** [comment]
Thanks, i change
since_prev = (ev.timeStamp - prev.lastEvent.timeStamp),
for
since_prev = (prev.lastEvent && ev.timeStamp - prev.lastEvent.timeStamp),
and work excellent
