### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by javismiles** [hammerjs/jquery.hammer.js#12]
hi :)
i see that latest version of your great jquery hammer plugin is
for Hammer.JS - v1.0.6
but latest hammer version is Hammer.JS - v1.0.10 
(im trying to upgrade to latest because of some issues im having with previous one)

Does your version work also with 1.0.10?

can i simply replace hammer code on top of the plugin with the 1.0.10 , would it then work?

thank you so much for your help

**Comment by javismiles** [comment]
aha i see that actually it says below
Hammer.VERSION = '1.0.10';
so i guess it was the right version :)
question if i may, in my web app , im using hammer to move elements,
it all works great on iphone, ipad, ipad mini and android nexus 5 smartphone,
but today i found out that on nexus 7 tablet (new version) and on Samsung android galaxy tab 3 tablet the dragging is not detected, doesnt work

can that be explained by the fact that i am using this older version ( Hammer.JS - v1.0.5 - 2013-04-07 ) ?
or is there any other reason ?

thank you so much
Jav

**Comment by jtangelder** [comment]
could be! or you havent called preventDefault, that also is importend... check the wiki at the hammer.js repo ;-)
