### ISSUE TITLE
Using jquery hammer in require...

### ISSUE THREAD

**Issue by hutber** [hammerjs/jquery.hammer.js#13]
I am building a Single Page Application using Backbone, but I am I have a feeling I am implementing this incorrectly. I get the following errors:

``` javascript
"NetworkError: 404 Not Found - http://sd.local/js/hammerjs.js"
hammerjs.js (line (null))
Error: Script error for: hammerjs http://requirejs.org/docs/errors.html#scripterror


var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

require.js (line 163)
```

My require config like this:

``` javascript
require.config({
    paths: {
        hammer: 'libs/plugins/hammer/hammer.min',
        jqueryhammer:'libs/plugins/hammer/jquery.hammer.min'
        }
});
```

The call to jquery.hammer

``` javascript
define([
    'hammer',
    'jqueryhammer'
], function (Hammer) {
    'use strict';
        //Calling the redner() function from this view will cause the above error.

```

**Comment by codearachnid** [comment]
I believe you might need to update your require.config to change the key:

```
require.config({
    paths: {
        hammerjs: 'libs/plugins/hammer/hammer.min',
        jqueryhammer:'libs/plugins/hammer/jquery.hammer.min'
        }
});
```

I noticed in the jquery.hammer.js file it requires the key as `hammerjs` vs `hammer`.

**Comment by codearachnid** [comment]
As a bit of followup I noticed that the documentation and other use cases all expect it to be `hammer` for the path key rather than `hammerjs` I am not sure why this change occured but seems to be breaking compatibility when requiring as AMD.

**Comment by hutber** [comment]
Somehow I missed these comments.

Thanks for the response. Indeed, hammerjs was the missing ingredient. :)
