### ISSUE TITLE
jquery.hammer.js 1.1.2 and  jquery.hammer.js 1.1.3 doesn't work on ie8 (jquery.hammer.js 1.1.1 is ok)

### ISSUE THREAD

**Issue by myggithub** [hammerjs/jquery.hammer.js#16]
Any idea how i can fix it? Thank you!

**Comment by benwick** [comment]
I think that is a mighty good question!

**Comment by kellyrmilligan** [comment]
sooo...no fix for this?

**Comment by jtangelder** [comment]
I guess i don't have any time left to also maintain the 1.x version. Any PR that fixes this will be accepted!

**Comment by arschmitz** [comment]
Closing we are not maintaining 1.x
