### ISSUE TITLE
jQuery.UI events don't work

### ISSUE THREAD

**Issue by TNKSoftware** [hammerjs/jquery.hammer.js#18]
It will disable jQuery.UI.draggable in case of such a code:
sp.draggable().hammer()

On the other hand, events of hammer.js don't fire in case of this:
sp.hammer().draggable()

But, in v1.0.5 - 2013-04-07, all events had fired.

**Comment by jtangelder** [comment]
I guess this is fixed in the 2.0 version, since it doesn't trigger a `drag` event anymore.
