### ISSUE TITLE
Loading the newest release (v1.0.0 - 2014-01-02)

### ISSUE THREAD

**Issue by pekala** [hammerjs/jquery.hammer.js#2]
I was getting jquery-hammerjs using Bower ("jquery-hammerjs": "*"). It downloaded file jquery.hammer.js to hammerjs folder. I then used RequireJS (with jquery injected using shim config) to load the plugin. 

After the latest release things changed and now Bower downloads two folders (hammerjs, and jquery-hammerjs). I can't figure out how to load the plugin now with RequireJS. Any hints on what the changes are about and what is the recommended approach to use it with AMD loader?

**Comment by eirikhm** [comment]
There is a change in the stand-alone release:

What was define(['hammer', 'jquery'], setup); is now define(['hammerjs', 'jquery'], setup); This also breaks backbone.hammer.js. 

What's the reason for this change?

**Comment by ahumphreys87** [comment]
@eirikhm the next version of the standalone release should fix these issues: I was having similar issues using this with backbone.hammer. This PR should solve the problem: https://github.com/EightMedia/jquery.hammer.js/pull/9

**Comment by eirikhm** [comment]
Excellent!

**Comment by jtangelder** [comment]
1.0.4 released, with this fixed :hammer:
