### ISSUE TITLE
Hammer 2.0

### ISSUE THREAD

**Issue by BBosman** [hammerjs/jquery.hammer.js#22]
Will this plugin be updated to Hammer 2.0?

**Comment by jtangelder** [comment]
Yes, it will, but for now a small plugin is already available at https://github.com/hammerjs/jquery.hammer.js

this will be extended with the full package so you only need to get one file.

**Comment by codepunkt** [comment]
Is there an estimated timeframe for this change?

**Comment by paintedbicycle** [comment]
What's the status of this? Is this repo going to be updated or will the other one linked above take over? I know things like backbone.hammer.js are depending on this one currently

**Comment by jtangelder** [comment]
Fixed!
