### ISSUE TITLE
Updating from 1.1.3 to 2.0.0 causes hammer() not a function

### ISSUE THREAD

**Issue by johnnyshankman** [hammerjs/jquery.hammer.js#46]
Was updating my packages.

Updating from 1.1.2 -> 1.1.3 was all good.

Updating from 1.1.3 -> 2.0.0 causes the `hammer` function to disappear.

`$(element).hammer().bind('event', handler)` ceases working where `$(element).hammer().on('event', handler)` had worked previously.

Am I missing something? Did the API change further? Do I need to separately include another package?

**Comment by BugDeveloper** [comment]
Same here.
