### ISSUE TITLE
Broken stopDefaultBrowserBehavior

### ISSUE THREAD

**Issue by borbit** [hammerjs/jquery.hammer.js#6]
Hi,

I've just noticed stopDefaultBrowserBehavior doesn't work at all. The trouble is here: 

https://github.com/EightMedia/jquery.hammer.js/blob/master/jquery.hammer-full.js#L314
https://github.com/EightMedia/jquery.hammer.js/blob/master/jquery.hammer-full.js#L321
https://github.com/EightMedia/hammer.js/blob/master/hammer.js#L310

"value" argument is missing. Sorry, I have no possibility to make a pull request at the moment.

**Comment by jtangelder** [comment]
should be fixed!
